# Configuración del sitio
url: "https://2624789.github.io/juanpablo.co"
baseurl: "/"

title: Juan Pablo Puentes Vargas
author: "2624789"
email: jp@juanpablo.co
phone: "+57(8) 8714193"
skype: "juanpablo.puentes"
description: >-
  Abogado especializado en tecnología y en propiedad intelectual
keywords: "Abogado, Tecnología, Derecho Informático, Propiedad Intelectual"
license: "CC-BY-SA"

social:
  - title: facebook
    url: https://www.facebook.com/juanpablo.pvco
  - title: twitter
    url: https://twitter.com/JuanPabloPV
  - title: instagram
    url: http://instagram.com/juanpablo.pv
  - title: envelope
    url: mailto:jp@juanpablo.co

github_username: "2624789"

# Configuración de compilación
markdown: kramdown
permalink: pretty
theme: minima
sass:
  style: compressed
plugins:
  - jekyll-feed
