# Configuraci칩n del sitio
url: ""
baseurl: ""

title: Jekyll Site
description: >-
  Sitio web personal est치tico hecho con Jekyll

# Configuraci칩n de compilaci칩n
markdown: kramdown
permalink: pretty
theme: minima
sass:
  style: compressed
plugins:
  - jekyll-feed
