# Configuración del sitio
url: ""
baseurl: ""

title: Juan Pablo Puentes Vargas
author: "2624789"
description: >-
  Sitio web personal estático hecho con Jekyll
keywords: "Jekyll, GitHub, Pages, Español, 2624789"
license: "CC-BY-SA"

social:
  - title: facebook
    url: https://www.facebook.com/juanpablo.pvco
  - title: twitter
    url: https://twitter.com/JuanPabloPV
  - title: instagram
    url: http://instagram.com/juanpablo.pv
  - title: envelope
    url: mailto:jp@juanpablo.co

github_username: "2624789"

# Configuración de compilación
markdown: kramdown
permalink: pretty
theme: minima
sass:
  style: compressed
plugins:
  - jekyll-feed
